global:
  topologyConfig: {}
  imagePullSecrets: []
  imageRegistry: ""
  appName: grimoirelab
  credentials:
    database:
      username: "root"
      password: "mar1adb4Gr1m0ir3Lab"
    opensearchNode:
      password: "admin"
    redis:
      password: "grimoirelab"

opensearch-node:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/opensearchproject/opensearch:2.11.1
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "500m"
        requests: "300m"
      memory:
        limits: "3000Mi"
        requests: "2000Mi"
  dependencies:
    storage:
      enabled: true
      volumes:
        - name: "opensearch-data"
          mountPath: "/usr/share/opensearch/data"
          type: pvc
          storageClass: efs-sc
          size: 10Gi
  service:
    targetPort: 9200
    scheme: passthrough
    type: ""
  extraEnvs:
    - name: cluster.name
      value: "opensearch-cluster"
    - name: node.name
      value: "opensearch-node1"
    - name: discovery.type
      value: "single-node"
    - name: bootstrap.memory_lock
      value: "true"
    - name: OPENSEARCH_JAVA_OPTS
      value: "-Xms2g -Xmx2g"

opensearch-dashboard:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/opensearchproject/opensearch-dashboards:2.11.1
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "200m"
        requests: "100m"
      memory:
        limits: "512Mi"
        requests: "256Mi"
  dependencies:
    storage:
      enabled: false
  service:
    targetPort: 5601
    scheme: passthrough
    type: ""
  extraEnvs: []

mordred:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/grimoirelab/grimoirelab:1.7.0
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "500m"
        requests: "200m"
      memory:
        limits: "1024Mi"
        requests: "512Mi"
  dependencies:
    storage:
      enabled: true
      volumes:
        - name: "mordred-setup"
          mountPath: "/home/grimoire/conf/setup.cfg"
          type: configmap
          subPath: "mordred-setup"
        - name: "mordred-projects"
          mountPath: "/home/grimoire/conf/projects.json"
          type: configmap
          subPath: "mordred-projects"
        - name: "mordred-log"
          mountPath: "/home/grimoire/logs"
          type: emptyDir
  service:
    targetPort: 8000
    scheme: passthrough
    type: ""
  extraEnvs: []

nginx:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/nginx:1.27.2
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "100m"
        requests: "50m"
      memory:
        limits: "256Mi"
        requests: "128Mi"
  dependencies:
    storage:
      enabled: true
      volumes:
        - name: "nginx-conf-template"
          mountPath: "/etc/nginx/templates/default.conf.template"
          type: configmap
          subPath: "nginx-conf-template"
        - name: "uwsgi-params"
          mountPath: "/etc/nginx/uwsgi_params"
          type: configmap
          subPath: "uwsgi-params"
        - name: "sortinghat-static"
          mountPath: "/sortinghat"
          type: pvc
  service:
    targetPort: 8000
    scheme: passthrough
    type: ""
  extraEnvs: []

sortinghat:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/grimoirelab/sortinghat:1.7.0
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "200m"
        requests: "100m"
      memory:
        limits: "512Mi"
        requests: "256Mi"
  dependencies:
    storage:
      enabled: true
      volumes:
        - name: "sortinghat-static"
          mountPath: "/opt/venv/lib/python3.9/site-packages/sortinghat/static"
          type: pvc
          storageClass: efs-sc
          size: 1Gi
  service:
    targetPort: 9314
    scheme: passthrough
    type: ""
  extraEnvs:
    - name: SORTINGHAT_SECRET_KEY
      value: "secret"
    - name: SORTINGHAT_DB_HOST
      value: "mariadb"
    - name: SORTINGHAT_DB_PORT
      value: "3306"
    - name: SORTINGHAT_DB_DATABASE
      value: "sortinghat_db"
    - name: SORTINGHAT_REDIS_HOST
      value: "redis-master"
    - name: SORTINGHAT_SUPERUSER_USERNAME
      value: "root"
    - name: SORTINGHAT_SUPERUSER_PASSWORD
      value: "root"
    - name: SORTINGHAT_ALLOWED_HOST
      value: "sortinghat,nginx,localhost,127.0.0.1,0.0.0.0,[::1]"

sortinghat-worker:
  install: true
  appConfig:
    replicas: 1
    image: docker.io/grimoirelab/sortinghat-worker:1.7.0
    labels: {}
    annotations: {}
    resources:
      cpu:
        limits: "200m"
        requests: "100m"
      memory:
        limits: "512Mi"
        requests: "256Mi"
  dependencies:
    storage:
      enabled: false
  service:
    scheme: passthrough
    type: ""
  extraEnvs:
    - name: SORTINGHAT_SECRET_KEY
      value: "secret"
    - name: SORTINGHAT_DB_HOST
      value: "mariadb"
    - name: SORTINGHAT_DB_PORT
      value: "3306"
    - name: SORTINGHAT_DB_DATABASE
      value: "sortinghat_db"
    - name: SORTINGHAT_REDIS_HOST
      value: "redis-master"

mariadb:
  install: false

redis:
  install: false
