---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mordred-config
  namespace: grimoire
data:
  projects.json: |
    {
      "grimoirelab": {
        "meta": {
          "title": "GrimoireLab"
        },
        "git": [
            "https://github.com/chaoss/grimoirelab.git"
          ]
      }
    }
  identities.yml: |
    - profile:
        name: GitHub No Replay
        is_bot: true
      email:
        - noreply@github.com

    - profile:
        name: Owlbert Einstein
      enrollments:
        - organization: Bitergia
      email:
        - owlbert_einstein@bitergia.com
      github:
        - owlbert_einstein

    - profile:
        name: Owlfred Hitchcock
      enrollments:
        - organization: Hogwarts
          end: 2012-05-31
        - organization: Bitergia
          start: 2012-06-01
      email:
        - owl_hitchcock@hogwarts.com
        - owl_hitchcock@bitergia.com
      github:
        - owl_hitchcock

    - profile:
        name: Owl Capone
      enrollments:
        - organization: Hogwarts
          end: 2012-05-31
        - organization: Bitergia
          start: 2012-06-01
      email:
        - owl_capone@bitergia.com
      github:
        - owl_capone
