global:
  topologyConfig: {}
  imagePullSecrets: []
  imageRegistry: ""
  appName: ""

install: true

appConfig:
  name: "mordred"
  replicas: 1
  image: docker.io/grimoirelab/grimoirelab:latest
  pullPolicy: "IfNotPresent"
  labels: {}
  annotations: {}
  resources:
    cpu:
      limits: ""
      requests: ""
    memory:
      limits: ""
      requests: ""

dependencies:
  storage:
    enabled: false
    volumes: []

service:
  labels: {}
  annotations: {}
  targetPort: 8000
  scheme: "http"
  type: ""  # Default to "ClusterIP"

extraEnvs: []
