apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.appConfig.name }}"
  labels:
    app: "{{ .Values.appConfig.name }}"
    {{- include "metadata.opensearchNode.service.labels" . | nindent 4 }}
  annotations:
    {{- include "metadata.opensearchNode.service.annotations" . | nindent 4 }}
spec:
  {{- include "template.service" . | nindent 2 }}
